Repository decide-part-aracena/decide-part-aracena, pull requests merged in 2022-12, with the labels that each got.

#96 feat #95: workflow de despliegue continuo en VPS
  .github/workflows/vpsdeploy.yml
Labels: CI/CD

#112 feat #102: Aplicar la ley d'Hont
  decide/postproc/views.py
  decide/voting/migrations/0006_auto_20221213_2104.py
  decide/voting/models.py
  decide/voting/views.py
Labels: enhancement

#126 Actualización del README
  README.md
Labels: documentation

#139 Importación de censo a partir de excel
  .gitignore
  decide/census/templates/excel.html
  decide/census/testImport.xlsx
  decide/census/testImport3.xlsx
  decide/census/testImport4.xlsx
  decide/census/testImport6.xlsx
  decide/census/tests.py
  decide/census/views.py
  decide/excel/excelPrueba.ods
  decide/excel/excelPrueba_H8kxVWR.ods
  decide/excel/excelPrueba_iZnwqkc.ods
  decide/testImport.xlsx
  docker-compose.yml
Labels: Censo

#144 fix #143: Arreglados mensajes de la pagina de inicio
  decide/base/templates/base/index.html
Labels: bug

#150 Importación de censo
  decide/census/views.py
Labels: Censo

#142 fix #120: Solucionado el boton de question Si/No.
  decide/decide/urls.py
  decide/voting/forms.py
  decide/voting/templates/preguntas.html
  decide/voting/tests.py
  decide/voting/views.py
Labels: bug

#159 feat #158: cambio color navbar a azul
  decide/base/templates/base_dashboard.html
Labels: enhancement
