Repository decide-part-aracena/decide-part-aracena, pull requests merged in 2022-11, with the labels that each got.

#49 fix #48: Arreglado fallo que impedía que iniciase la aplicación
  .gitignore
  decide/census/urls.py
  decide/decide/settings.py
  decide/decide/urls.py
  decide/local_settings.example.py
Labels: bug

#58 feat #53 #15, documento de gestión de incidencias y comienzo de visualización de datos en tiempo real
  decide/base/templates/base/index.html
  decide/visualizer/templates/visualizer/visualizer.html
  decide/visualizer/views.py
  doc/gestión de incidencias.md
Labels: documentation, enhancement, Visualización

#59 feature #36: ordenar votaciones
  decide/base/templates/base_dashboard.html
  decide/base/urls.py
  decide/booth/templates/booth/booth.html
  decide/decide/urls.py
  decide/visualizer/templates/visualizer/visualizer.html
  decide/voting/forms.py
  decide/voting/templates/crearPreguntas.html
  decide/voting/templates/create_voting.html
  decide/voting/templates/preguntas.html
  decide/voting/templates/showUpdateQuestions.html
  decide/voting/templates/sorted_by_endDate.html
  decide/voting/templates/sorted_by_name.html
  decide/voting/templates/sorted_by_startDate.html
  decide/voting/templates/voting_details.html
  decide/voting/templates/voting_list.html
  decide/voting/urls.py
  decide/voting/views.py
Labels: enhancement
